/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public.auth.register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public.auth.login'
import { Route as PublicAuthCallbackRouteImport } from './routes/_public.auth.callback'
import { Route as DashboardDashboardOrganizationsIndexRouteImport } from './routes/_dashboard/dashboard.organizations.index'
import { Route as DashboardDashboardOrganizationsNewRouteImport } from './routes/_dashboard/dashboard.organizations.new'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthCallbackRoute = PublicAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardDashboardOrganizationsIndexRoute =
  DashboardDashboardOrganizationsIndexRouteImport.update({
    id: '/dashboard/organizations/',
    path: '/dashboard/organizations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardOrganizationsNewRoute =
  DashboardDashboardOrganizationsNewRouteImport.update({
    id: '/dashboard/organizations/new',
    path: '/dashboard/organizations/new',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth/callback': typeof PublicAuthCallbackRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/dashboard/organizations/new': typeof DashboardDashboardOrganizationsNewRoute
  '/dashboard/organizations': typeof DashboardDashboardOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth/callback': typeof PublicAuthCallbackRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/dashboard/organizations/new': typeof DashboardDashboardOrganizationsNewRoute
  '/dashboard/organizations': typeof DashboardDashboardOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_public/auth/callback': typeof PublicAuthCallbackRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/register': typeof PublicAuthRegisterRoute
  '/_dashboard/dashboard/organizations/new': typeof DashboardDashboardOrganizationsNewRoute
  '/_dashboard/dashboard/organizations/': typeof DashboardDashboardOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/organizations/new'
    | '/dashboard/organizations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/organizations/new'
    | '/dashboard/organizations'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_public'
    | '/_public/'
    | '/_public/auth/callback'
    | '/_public/auth/login'
    | '/_public/auth/register'
    | '/_dashboard/dashboard/organizations/new'
    | '/_dashboard/dashboard/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/register': {
      id: '/_public/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/callback': {
      id: '/_public/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof PublicAuthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_dashboard/dashboard/organizations/': {
      id: '/_dashboard/dashboard/organizations/'
      path: '/dashboard/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardDashboardOrganizationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/organizations/new': {
      id: '/_dashboard/dashboard/organizations/new'
      path: '/dashboard/organizations/new'
      fullPath: '/dashboard/organizations/new'
      preLoaderRoute: typeof DashboardDashboardOrganizationsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardOrganizationsNewRoute: typeof DashboardDashboardOrganizationsNewRoute
  DashboardDashboardOrganizationsIndexRoute: typeof DashboardDashboardOrganizationsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardOrganizationsNewRoute:
    DashboardDashboardOrganizationsNewRoute,
  DashboardDashboardOrganizationsIndexRoute:
    DashboardDashboardOrganizationsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthCallbackRoute: typeof PublicAuthCallbackRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthCallbackRoute: PublicAuthCallbackRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
